### ISSUE TITLE
Version skip to 1.40

### ISSUE THREAD

**Issue by arkadiuszczapiewskinordea** [NordeaOSS/devtool#10]
Hi Guys!

As we needed to publish "new" versions to change repository links in an organization, internally we have v1.39, even if it is in fact still 1.37. So can we "magically" jump to v1.40, so I can get latest updates (especially: Java built-in) and be in line with GitHub?

If it's possible - thanks in advance!!!

**Comment by holmbech** [comment]
Hi,

Let us do it this time. I would recommend, that you next time use patch versions to create internal releases. eg 1.37.1 and 1.37.2.

I can do the changes later tonight.

**Comment by holmbech** [comment]
Versions now updated

**Comment by arkadiuszczapiewskinordea** [comment]
You are definitely right. I'll do that in the future, but hope it will not be needed anymore.

Anyway - really thanks!!!!
