### ISSUE TITLE
Environment variables when uninstalling a package

### ISSUE THREAD

**Issue by arkadiuszczapiewskinordea** [NordeaOSS/devtool#4]
To consider: when uninstalling package, PATH and other variables (e.g. JAVA_HOME) are not updated. They can be switched to other version with:
devtool -setup <tool> <version>
but the problem is e.g. for JDKs. If you uninstall JDK that has been configured in JAVA_HOME, DevTool stops working. The solution could be to update path to any other (latest?) existing JDK. Or another idea: maybe DevTool should be delivered with its own, independent JDK - in this case we can also get rid of Java 9 issue.

**Comment by holmbech** [comment]
It's well worth considering bundling a jdk with devtool.
That will solve a couple a things.

**Comment by holmbech** [comment]
Will be fixed by bundling a jdk. See #3
